/**
 * Shared domain types for the NCLEX Voice Quiz.
 *
 * This file is compiled into BOTH the Node server and the browser app, so it must stay free of
 * Node- or DOM-specific code. Every import of it must use the `.js` extension
 * (`import ... from "../shared/types.js"`).
 */

/** NCLEX-RN Client Needs subcategories (the eight content areas of the test plan). */
export const CATEGORY_IDS = [
  "management_of_care",
  "safety_and_infection_control",
  "health_promotion_and_maintenance",
  "psychosocial_integrity",
  "basic_care_and_comfort",
  "pharmacological_and_parenteral_therapies",
  "reduction_of_risk_potential",
  "physiological_adaptation",
] as const;
export type CategoryId = (typeof CATEGORY_IDS)[number];

/** Every question has exactly three answer options, labelled A, B and C (in that order). */
export const OPTION_LABELS = ["A", "B", "C"] as const;
export type OptionLabel = (typeof OPTION_LABELS)[number];

export const DIFFICULTIES = ["easy", "medium", "hard"] as const;
export type Difficulty = (typeof DIFFICULTIES)[number];

/** Where a question came from: shipped with the app, generated by Claude, or imported from JSON. */
export const QUESTION_SOURCES = ["bundled", "ai", "imported"] as const;
export type QuestionSource = (typeof QUESTION_SOURCES)[number];

/** The six functions of the NCSBN Clinical Judgment Measurement Model (Layer 3). */
export const CLINICAL_JUDGMENT_STEPS = [
  "recognize_cues",
  "analyze_cues",
  "prioritize_hypotheses",
  "generate_solutions",
  "take_action",
  "evaluate_outcomes",
] as const;
export type ClinicalJudgmentStep = (typeof CLINICAL_JUDGMENT_STEPS)[number];

export interface AnswerOption {
  label: OptionLabel;
  /** Option text as shown on screen and read aloud. */
  text: string;
  /**
   * Why this option is right (for the keyed answer) or wrong (for distractors).
   * Shown and spoken after the learner answers. Must be a complete, self-contained sentence or two.
   */
  rationale: string;
}

export interface Question {
  /** Unique id. Bundled: `<prefix>-<nnn>` (e.g. `moc-001`). Generated: `ai-<timestamp>-<n>`. */
  id: string;
  /** The question as shown on screen and read aloud. Plain text, no markdown. */
  stem: string;
  /** Exactly three options with labels "A", "B", "C" in order. */
  options: AnswerOption[];
  /** Label of the single correct option. */
  correct: OptionLabel;
  category: CategoryId;
  /** Activity statement from the blueprint this question tests, e.g. "Establishing Priorities". */
  subtopic: string;
  clinicalJudgmentStep?: ClinicalJudgmentStep;
  difficulty: Difficulty;
  source: QuestionSource;
  /** One short paragraph with the key takeaway (the "why it matters"). */
  teachingPoint?: string;
  /** Names of study sources / guidelines the question was grounded in. */
  references?: string[];
  tags?: string[];
  /** ISO-8601 timestamp. */
  createdAt: string;
}

/** On-disk format for question banks (bundled seed files, generated bank, imports). */
export interface QuestionFile {
  version: 1;
  questions: Question[];
}

export type InputMode = "voice" | "tap" | "keyboard";

export interface Attempt {
  id: string;
  sessionId: string;
  questionId: string;
  category: CategoryId;
  chosen: OptionLabel;
  correct: OptionLabel;
  isCorrect: boolean;
  /** ISO-8601 timestamp. */
  answeredAt: string;
  responseMs?: number;
  inputMode: InputMode;
}

export interface CategoryStats {
  category: CategoryId;
  attempted: number;
  correct: number;
  /** correct / attempted, or null when nothing has been attempted. */
  accuracy: number | null;
}

export interface SessionSummary {
  sessionId: string;
  startedAt: string;
  answered: number;
  correct: number;
}

export interface Stats {
  totalAttempted: number;
  totalCorrect: number;
  accuracy: number | null;
  byCategory: CategoryStats[];
  /** Most recent first, at most 20. */
  recentSessions: SessionSummary[];
  /**
   * Categories the learner is weakest in: attempted >= 3 and accuracy below 70%, worst first.
   * Empty until enough questions have been answered.
   */
  weakCategories: CategoryId[];
}

// ---------------------------------------------------------------------------------------------
// API request / response shapes (see docs/API.md)
// ---------------------------------------------------------------------------------------------

export interface QuizStartRequest {
  /** 1..50 */
  count: number;
  /** Restrict to these categories; omitted/empty = all categories weighted by the blueprint. */
  categories?: CategoryId[];
  /** Restrict to these sources; omitted/empty = all. */
  sources?: QuestionSource[];
  difficulty?: Difficulty[];
  /** Bias selection toward the learner's weak categories (default true). */
  adaptive?: boolean;
  /** Prefer questions not answered in the last 7 days (default true). */
  avoidRecent?: boolean;
}

export interface QuizStartResponse {
  sessionId: string;
  questions: Question[];
}

export interface AttemptRequest {
  sessionId: string;
  questionId: string;
  chosen: OptionLabel;
  inputMode: InputMode;
  responseMs?: number;
}

export interface AttemptResponse {
  attempt: Attempt;
  isCorrect: boolean;
  correct: OptionLabel;
}

export interface GenerateRequest {
  /** 1..20 */
  count: number;
  /** Omitted/empty = spread across all categories following the blueprint percentages. */
  categories?: CategoryId[];
  difficulty?: Difficulty;
  clinicalJudgmentSteps?: ClinicalJudgmentStep[];
  /** Ids of study sources whose text should ground the questions. */
  sourceIds?: string[];
  /** Let Claude research current NCLEX/NCSBN and clinical guidance online before writing. */
  research?: boolean;
  /** Weight generation toward the learner's weak categories (uses /api/stats). */
  targetWeakAreas?: boolean;
  /** Free-text focus, e.g. "insulin types and peak times". */
  focus?: string;
  /** Save generated questions into the bank (default true). */
  save?: boolean;
}

export interface GenerateResponse {
  questions: Question[];
  /** Present when `research` was requested: the brief Claude compiled before writing questions. */
  researchBrief?: string;
  model: string;
  usage: { inputTokens: number; outputTokens: number };
  /** Non-fatal problems, e.g. questions dropped for failing validation. */
  warnings: string[];
}

export type StudySourceKind = "text" | "file" | "url";

export interface StudySource {
  id: string;
  name: string;
  kind: StudySourceKind;
  /** Length of the extracted text in characters. */
  chars: number;
  addedAt: string;
  /** First ~200 characters of the text. */
  preview: string;
  url?: string;
}

export interface VoiceSettings {
  /** Read questions and feedback aloud. */
  enabled: boolean;
  /** Speech rate multiplier, 0.5..2 (1 = normal). */
  rate: number;
  /** Preferred browser voice name; undefined = browser default. */
  voiceName?: string;
  /** Start listening for a spoken answer automatically after the question is read. */
  autoListen: boolean;
  /** Speak the rationale after answering (not just "correct"/"wrong"). */
  readRationale: boolean;
}

export interface Settings {
  /** Claude model id used for generation. */
  model: string;
  /** True when an API key is configured (env var or saved settings). The key itself is never returned. */
  hasApiKey: boolean;
  /** e.g. "sk-ant-…7f2a" so the user can tell which key is stored. */
  apiKeyHint?: string;
  /** True when the key comes from the ANTHROPIC_API_KEY environment variable (read-only in the UI). */
  apiKeyFromEnv: boolean;
  voice: VoiceSettings;
  /** Default number of questions when starting a quiz. */
  defaultCount: number;
}

export interface BlueprintCategory {
  id: CategoryId;
  /** Official subcategory name, e.g. "Management of Care". */
  name: string;
  /** Parent Client Needs category, e.g. "Safe and Effective Care Environment". */
  group: string;
  minPercent: number;
  maxPercent: number;
  /** One-paragraph description of what the subcategory covers. */
  description: string;
  /** Related activity statements / content areas listed under the subcategory. */
  activityStatements: string[];
}

export interface Blueprint {
  name: string;
  effective: string;
  source: string;
  examFormat: string;
  categories: BlueprintCategory[];
  integratedProcesses: string[];
  clinicalJudgmentSteps: { id: ClinicalJudgmentStep; name: string; description: string }[];
}
